# Site settings
title: Dylan Doherty
author:
  name: Dylan Doherty
  email: dylancdoherty@protonmail.com
description: "The Internet home of Dylan Doherty"

# Build settings

remote_theme: pmarsceill/just-the-docs
